USE `Tracksz`;

ALTER TABLE ShippingZoneToRegion
CHANGE ZipCodeMin ZipCodeMin MEDIUMINT(5) UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE ShippingZoneToRegion
CHANGE ZipCodeMax ZipCodeMax MEDIUMINT(5) UNSIGNED NOT NULL DEFAULT 99950;