CREATE TABLE `postagesettings` ( `Id` int(11) NOT NULL,
         `OperatingSystem` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
         `MaxWeight` int(11) DEFAULT NULL,
         `DeliveryConfirmation` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
         `MinOrderTotalDelivery` double(5,
        2) NOT NULL DEFAULT '0.00',
         `SignatureConfirmation` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
         `ConsolidatorLabel` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
         `IncludeInsurance` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
         `MinOrderTotalInsurance` double(5,
        2) DEFAULT '0.00',
         `RoundDownPartial` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
         `EstimatePostage` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
         `MaxPostageBatch` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
         `CustomsSigner` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
         `DefaultWeight` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
         `FlatRatePriority` tinyint(1) NOT NULL DEFAULT '0',
         `GlobalWeight` tinyint(1) NOT NULL,
         `UserId` int(11) DEFAULT NULL,
         `Updated` datetime DEFAULT CURRENT_TIMESTAMP,
         `Created` datetime DEFAULT CURRENT_TIMESTAMP ) ENGINE=InnoDB DEFAULT CHARSET=latin1; ALTER TABLE `postagesettings` ADD PRIMARY KEY (`Id`); ALTER TABLE `postagesettings` MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT; COMMIT;