CREATE TABLE `shipping_templates` ( `Id` int(11) NOT NULL,
         `ProductId` int(11) DEFAULT NULL,
         `AbeBooks` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
         `Alibris` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
         `Amazon` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
         `AmazonEurope` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
         `BarnesAndNoble` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
         `Biblio` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
         `Chrislands` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
         `eBay` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
         `eCampus` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
         `TextbookRush` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
         `TextbookX` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
         `Valore` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
         `Default` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
         `UserId` int(11) DEFAULT NULL,
         `MarketPlaceId` int(11) DEFAULT NULL,
         `StoreId` int(11) DEFAULT NULL,
         `Created` datetime DEFAULT CURRENT_TIMESTAMP,
         `Updated` datetime DEFAULT CURRENT_TIMESTAMP ) ENGINE=InnoDB DEFAULT CHARSET=latin1; ALTER TABLE `shipping_templates` ADD PRIMARY KEY (`Id`); ALTER TABLE `shipping_templates` MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT,
         AUTO_INCREMENT=10; COMMIT;